In [2]:
import pandas as pd

otu_info = pd.read_csv("../data/raw/otu_info.csv")

otu_info = otu_info.assign(seq_len = lambda x: x.Seq.apply(lambda y: len(y)))
otu_info

seq_max_len = otu_info.seq_len.max()

In [3]:
import numpy as np
def pad(A, n):
    return np.pad(A,((0,n), (0,0)))

In [12]:
def onehot(s):
    nm = {"A": 0,
        "C": 1,
        "T": 2,
        "G": 3}
    ind = [nm[x] for x in s] 
    return np.eye(4).astype(np.uint8)[ind]


In [5]:
row

NameError: name 'row' is not defined

In [6]:
dataset = []
for i, row in otu_info.iterrows():
    s = row.Seq
    l = row.seq_len
    d = seq_max_len - l

    oh_array = pad(onehot(s),d)
    dataset.append({"ID": row.ID,
                    "taxon": row.taxon,
                    "seq": oh_array})


dataset

[{'ID': 'OTU_1',
  'taxon': 'Oulimnius tuberculatus',
  'seq': array([[0, 0, 1, 0],
         [0, 0, 1, 0],
         [0, 0, 1, 0],
         [1, 0, 0, 0],
         [0, 0, 1, 0],
         [0, 1, 0, 0],
         [0, 0, 1, 0],
         [0, 0, 0, 1],
         [0, 1, 0, 0],
         [0, 1, 0, 0],
         [1, 0, 0, 0],
         [1, 0, 0, 0],
         [0, 1, 0, 0],
         [1, 0, 0, 0],
         [0, 0, 1, 0],
         [0, 0, 1, 0],
         [0, 0, 0, 1],
         [0, 1, 0, 0],
         [0, 1, 0, 0],
         [0, 1, 0, 0],
         [1, 0, 0, 0],
         [0, 0, 1, 0],
         [1, 0, 0, 0],
         [0, 0, 0, 1],
         [1, 0, 0, 0],
         [0, 0, 0, 1],
         [0, 0, 0, 1],
         [1, 0, 0, 0],
         [0, 0, 1, 0],
         [0, 1, 0, 0],
         [1, 0, 0, 0],
         [0, 0, 1, 0],
         [0, 1, 0, 0],
         [0, 0, 1, 0],
         [0, 0, 0, 1],
         [0, 0, 1, 0],
         [0, 0, 1, 0],
         [0, 0, 0, 1],
         [1, 0, 0, 0],
         [0, 0, 1, 0],
         [0, 0, 1, 

In [7]:
import pickle
with open("../data/processed/dataset.pkl", "wb") as f:
    pickle.dump(dataset, f)

In [8]:
from sklearn.metrics import jaccard_score

jaccard_score([0,1,0], [1,0,0])

0.0

In [9]:
A1 = onehot("ACTGA")
A2 = onehot("AATGA")
A3 = onehot("GACAG")

print(A1)
print(A2)
print(A3)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]]
[[1 0 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]]
[[0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 0 1]]


In [11]:
def jaccard(A, B):
    d = np.sum(A*B, axis=1)
    return np.sum(d)/len(d)

print(jaccard(A1, A1))
print(jaccard(A1, A2))
print(jaccard(A2, A3))
print(jaccard(A1, A3))



1.0
0.8
0.2
0.0
